import * as React from "react";

import Button from "../components/common/Button.tsx";
import Input from "../components/common/Input.tsx";
import Modal from "../components/common/Modal.tsx";
import type { ModalProps } from "../types/modals.ts";

function ConnectToServerModal(props: ModalProps) {
  const [value, setValue] = React.useState("");

  return (
    <Modal
      className="w-[480px]"
      title={"Connect to server:"}
      footer={<Button onClick={() => props.onClose(value)}>Connect</Button>}
    >
      <p>Enter ID generated by 3D Map Fixed Helper mod on launch</p>
      <Input
        type="text"
        value={value}
        onChange={(event) => setValue(event.target.value)}
        autoFocus={true}
        className="mt-2 w-64"
        placeholder="ID"
      />
    </Modal>
  );
}

export default ConnectToServerModal;
